runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "300d 5h"

handlers:
- url: /manifest.webapp
  static_files: manifest/manifest.json
  upload: manifest/manifest.json
  http_headers:
    Content-Type: application/x-web-app-manifest+json

- url: /manifest-noads.webapp
  static_files: manifest/manifest-noads.json
  upload: manifest/manifest-noads.json
  http_headers:
    Content-Type: application/x-web-app-manifest+json

- url: /static/*
  static_dir: static
  http_headers:
    Vary: Accept-Encoding
- url: /transient/*
  static_dir: transient
  http_headers:
    Vary: Accept-Encoding
  expiration: "0d 1h"

- url: /robots.txt
  static_files: transient/robots.txt
  upload: transient/robots.txt

- url: /BingSiteAuth.xml
  static_files: static/BingSiteAuth.xml
  upload: static/BingSiteAuth.xml

- url: /channel.html
  static_files: static/channel.html
  upload: static/channel.html

- url: /gameon/static/*
  static_dir: gameon/static
  http_headers:
    Vary: Accept-Encoding


- url: /favic(.+)
  static_files: static/icons/favic\1
  upload: static/icons/favic(.*)
  http_headers:
    Vary: Accept-Encoding
- url: /apple(.+)
  static_files: static/icons/apple\1
  upload: static/icons/apple(.*)
  http_headers:
    Vary: Accept-Encoding
- url: /mstile(.+)
  static_files: static/icons/mstile\1
  upload: static/icons/mstile(.*)
  http_headers:
    Vary: Accept-Encoding
- url: /android(.+)
  static_files: static/icons/android\1
  upload: static/icons/android(.*)
  http_headers:
    Vary: Accept-Encoding
- url: /browserconfig.xml
  static_files: static/icons/browserconfig.xml
  upload: static/icons/browserconfig.xml
  http_headers:
    Vary: Accept-Encoding

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

instance_class: F1
#automatic_scaling:
#  max_pending_latency: 7.5s
# automatic_scaling:
#   min_idle_instances: 2
#   max_pending_latency: 4.5s

# YOLO cost saving autoscaling
automatic_scaling:
  max_idle_instances: 1
  target_cpu_utilization: .95
  target_throughput_utilization: .95
  min_pending_latency: 300ms
  max_pending_latency: 15000ms
  max_concurrent_requests: 80


inbound_services:
- warmup

builtins:
- appstats: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules.*$
